# Generated by Django 2.2.9 on 2020-01-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
